development: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME']%>
  pool: 5
  username: <%= ENV['DB_USER']%>
  host: <%= ENV['DB_HOST']%>

test:
  <<: *default
  database: diner_test