# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 786b28478cfeba737f74f27ee0f2a2ad164ff64bab8bdad50105deff15ae47afdbfccf1de9d759b02bfce8d4a1cc95f1a4aa811932b51562541c932e5143ff9d

test:
  secret_key_base: 1dddeb249ef9b0470260be69f2b4e0227622b2049b9badc3cf87f4402204d5a71cb399429b033bd8ae9a4beb609884f6ffca9dc76bebf455b3db1810d49a3b5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
